<?php

namespace Projet\MapsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsRepository extends EntityRepository
{
}
