Locations:
    type: entity
    table: locations
    id:
        idlocation:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idLocation
            generator:
                strategy: IDENTITY
    fields:
        nomlocation:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: nomLocation
        latitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        longitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
    lifecycleCallbacks: {  }
