Reclamation:
    type: entity
    table: reclamation
    indexes:
        idClient:
            columns:
                - idClient
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        question:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        reponse:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
    manyToOne:
        idclient:
            targetEntity: Personne
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idClient:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
